name: DynamoDB Tests
on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      dynamo:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./run-tests
        env:
          AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
          AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          AWS_DEFAULT_REGION: us-west-2
